# Generated by Django 6.0.4 on 2026-06-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddefinition',
            name='generation_mode',
            field=models.CharField(choices=[('nlp', 'NLP'), ('ai', 'AI')], default='nlp', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='generation_mode',
            field=models.CharField(choices=[('nlp', 'NLP'), ('ai', 'AI')], default='nlp', max_length=10),
        ),
        migrations.CreateModel(
            name='AIQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attempt', to='documents.quizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='AIQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_answers', to='documents.generatedquestion')),
                ('ai_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='documents.aiquizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_mode', models.CharField(choices=[('nlp', 'NLP'), ('ai', 'AI')], max_length=10)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('max_questions', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.questionset'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='documents.questionset'),
        ),
    ]
