# Generated by Django 6.0.4 on 2026-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_extracteddefinition_generation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquizattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
